// <auto-generated />
using IEPCompanion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IEPCompanion.Migrations
{
    [DbContext(typeof(IEPCompanionContext))]
    [Migration("20231127000524_AddIEPSchoolYearPersonId")]
    partial class AddIEPSchoolYearPersonId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IEPCompanion.Models.IEP", b =>
                {
                    b.Property<int>("IEPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("int");

                    b.HasKey("IEPId");

                    b.ToTable("IEPs");
                });

            modelBuilder.Entity("IEPCompanion.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Category = "Administrator",
                            FirstName = "Harold",
                            LastName = "Gold"
                        },
                        new
                        {
                            PersonId = 2,
                            Category = "Teacher",
                            FirstName = "Mary",
                            LastName = "Berry"
                        },
                        new
                        {
                            PersonId = 3,
                            Category = "Student",
                            FirstName = "Aaron",
                            LastName = "Holland"
                        },
                        new
                        {
                            PersonId = 4,
                            Category = "Parent",
                            FirstName = "Mary",
                            LastName = "Holland"
                        });
                });

            modelBuilder.Entity("IEPCompanion.Models.PersonIEP", b =>
                {
                    b.Property<int>("PersonIEPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IEPId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonIEPId");

                    b.HasIndex("IEPId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonIEPs");
                });

            modelBuilder.Entity("IEPCompanion.Models.PersonIEP", b =>
                {
                    b.HasOne("IEPCompanion.Models.IEP", "Iep")
                        .WithMany("JoinEntities")
                        .HasForeignKey("IEPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IEPCompanion.Models.Person", "person")
                        .WithMany("JoinEntities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iep");

                    b.Navigation("person");
                });

            modelBuilder.Entity("IEPCompanion.Models.IEP", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("IEPCompanion.Models.Person", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
